name: Update Content List for GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Optional: Run daily at midnight

jobs:
  update-github-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install node-fetch  # Install dependencies if needed (like node-fetch)

      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: node contentListUpdater.js  # Run the JavaScript file to generate files.json

      - name: Commit and push changes to main
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add files.json
          git commit -m 'Update files.json with latest Kotlin files' || echo "No changes to commit"
          git push origin main

      - name: Checkout github_pages_from_main branch
        run: git checkout github_pages_from_main

      - name: Merge main into github_pages_from_main
        run: |
          git pull origin main
          git merge main
          git push origin github_pages_from_main

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_branch: github_pages_from_main  # Deploy branch for GitHub Pages
          publish_dir: ./kotlinDSAWithIntellijIdea  # Directory containing the website files
